# Generated by Django 5.1.3 on 2024-12-01 05:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_event_user_alter_user_token_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='color',
            field=models.CharField(default='#000000', help_text='Color of the calendar in hex format (e.g., #FF5733)', max_length=7),
        ),
        migrations.AddField(
            model_name='event',
            name='color',
            field=models.CharField(default='#000000', help_text='Color of the calendar in hex format (e.g., #FF5733)', max_length=7),
        ),
        migrations.AlterField(
            model_name='user',
            name='token_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 1, 5, 46, 21, 292218)),
        ),
    ]
