# Generated by Django 4.2.16 on 2024-11-20 06:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_google_access_token_user_google_refresh_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='googleSignUpOnly',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='token_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 20, 6, 44, 52, 751147)),
        ),
    ]
