# Generated by Django 5.1.3 on 2024-11-21 22:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_googlesignuponly_alter_user_token_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 21, 22, 31, 30, 746408)),
        ),
    ]
